### PR TITLE
Setup os dependent machine config extensions.

### LINKED ISSUE #267: OKD: Choosing the right machine config extension on FCOS
**Description**

The machine config operator handles RHCOS and FCOS differently when effectuating machine config extensions.

On RHCOS it uses a hardcoded list which is then translated into the actual packages. In our case, sandboxed-containers are translated into kata-containers and then rpm-ostree is called.

On FCOS it just pipes the extensions directly into rpm-ostree, which means that in the current implementation it tries to install sandboxed-containers which doesn't exist in FCOS yum repo.

**Steps to reproduce the issue:**
1. Install OKD.
2. Enable the fcos.repo yum repo.
3. Install sandboxed-containers and create a kataconfig

**Describe the results you received:**

On FCOS, the worker node complains about there is no rpm package sandboxed-containers.

**Describe the results you expected:**

The package kata-containers would be installed.

**Additional environment details (platform, options, etc.):**
OKD 4.12 with FCOS.

### PR DESCRIPTION
**Pull request by smuda**
**- Description of the problem which is fixed/What is the use case**

The machine config operator handles RHCOS and FCOS differently when effectuating machine config extensions.

On RHCOS it uses a hardcoded list which is then translated into the actual packages. In our case, `sandboxed-containers` are translated into `kata-containers` and then rpm-ostree is called.

On FCOS it just pipes the extensions directly into rpm-ostree, which means that in the current implementation it tries to install `sandboxed-containers` which doesn't exist in FCOS yum repo.

Fixes #267 

**- What I did**

I added an OS detection mechanism and if it's RHCOS I use `sandboxed-containers` as extension, otherwise I use `kata-containers`. 

In theory it's unfortunate that it's the OS of the operator that I use for guessing what OS the actual worker node has, but I've never heard of an OCP with FCOS or OKD with RHCOS so I think it's a reasonable assumption.

**- How to verify it**

1. Install OKD.
2. Enable the fcos.repo yum repo
3. Build from source according to [DEVELOPMENT.md](https://github.com/openshift/sandboxed-containers-operator/blob/main/docs/DEVELOPMENT.md).
4. Install from OKD console.

**- Description for the changelog**

Support for choosing the right RPM package on OKD/FCOS.

### CODE REVIEW

File: controllers/openshift_controller.go [hunk 1]
```diff
@@ -473,6 +474,21 @@ func (r *KataConfigOpenShiftReconciler) newMCForCR(machinePool string) (*mcfgv1.
...
+	// send in "kata-containers".
+	// Both are later send to rpm-ostree for installation.
+	//
+	// As RHCOS is rather special variant, use "kata-containers" by default.
+	var extensions = []string{"kata-containers"}
+
+	if r.Os.IsEL() {
+		extensions = []string{"sandboxed-containers"}
+	}
+	if r.Os.IsFCOS() {
```
Comment (bpradipt) [inline controllers/openshift_controller.go:488]: Is this condition needed since default for extensions is "kata-containers" ?

File: controllers/osrelease.go [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+// OperatingSystem is a wrapper around a subset of the os-release fields
+// and also tracks whether ostree is in use.
+type OperatingSystem struct {
+	// id is the ID field from the os-release
+	id string
+	// variantID is the VARIANT_ID field from the os-release
+	variantID string
+	// version is the VERSION, RHEL_VERSION, or VERSION_ID field from the os-release
+	version string
+	// osrelease is the underlying struct from github.com/ashcrow/osrelease
```
Comment (bpradipt) [inline controllers/osrelease.go:31]: I was bit sceptic about using the osrelease project as it has not been updated since last 6 years. However found that MCO is also using  it in `machine-config-operator/pkg/daemon/osrelease.go`.  So should be ok :-)

File: controllers/openshift_controller.go (hunk 1 above)
Comment (smuda) [reply controllers/openshift_controller.go:488]: Not really, just wanted to be explicit. I'll remove it.

Comment (bpradipt) [reply controllers/openshift_controller.go:488]: You can add a comment mentioning that the default applies to FCOS.

**Review by pmores — APPROVED** [review]
Looks good to me, thanks @smuda !

File: controllers/openshift_controller.go (hunk 1 above)
Comment (smuda) [reply controllers/openshift_controller.go]: I've removed the if-clause and added a comment that it applies to FCOS.

Comment (smuda) [reply controllers/openshift_controller.go]: @bpradipt Do you think we could resolve this conversation?

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @smuda

File: controllers/openshift_controller.go (hunk 1 above)
Comment (bpradipt) [reply controllers/openshift_controller.go]: Yeah. Thanks @smuda
